### ISSUE TITLE
Creating a new wand can bring back previously deleted wand files

### ISSUE THREAD

**Issue by Josh194** [MegaGlub/spell-builder#19]
Steps to reproduce (from empty save):
- Create a new wand
- Delete the wand (can verify that file is removed from `data/wands`)
- Create another wand with a different name

`data/wands` now contains both the second and first wand files, despite the first being removed previously.
This is not just a file creation bug; the old wand file contains the same internal data as it had before deletion.
Note, however, that the old wand does not show up in the UI (presumably it would on a reload, but I cannot test currently due to #17).

**Comment by MegaGlub** [comment]
Issue with removal not properly removing the wand from wandList, then the next trigger of the wand saving function saving the wandList again. Will have a fix shortly.
